### ISSUE TITLE
booleans seem not to toggle properly

### ISSUE THREAD

**Issue by ktiedt** [charbelrami/polymerizr#1]
ie: add a paper-button, toggle raised, the button raises, toggle it back off and it will not un-raise.

**Comment by charbelrami** [comment]
Thanks @ktiedt . Boolean is toggled properly, but the property `raised` also adds the property `elevation`. Then, when `raised` is removed, `elevation` remains.

**Comment by ktiedt** [comment]
Ahh interesting side effect
